# Generated by Django 2.0.2 on 2018-04-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pubDate',
            field=models.DateTimeField(db_column='pub_date'),
        ),
    ]
