# Generated by Django 2.0.2 on 2018-03-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(db_column='first_name', max_length=30)),
                ('lastName', models.CharField(db_column='last_name', max_length=30)),
            ],
            options={
                'verbose_name': '',
                'db_table': 't_person',
            },
        ),
    ]
