# Generated by Django 2.0.2 on 2018-04-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180401_1135'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='t_user',
        ),
    ]
