# Generated by Django 2.0.2 on 2018-04-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180401_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_time',
            field=models.TimeField(default=None),
        ),
    ]
