# Generated by Django 2.0.2 on 2018-04-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_other_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='other_time',
        ),
    ]
