# Generated by Django 2.0.2 on 2018-04-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180402_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
